[build]
 command = "yarn dist"
 publish = "dist"

[[headers]]
 for = "/*"

 [headers.values]
  Feature-Policy = "default 'self'"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Frame-Options = "DENY"
  X-Xss-Protection = "1; mode=block; report=https://ldesgoui.report-uri.com/r/d/xss/enforce"
  X-Content-Type-Options = "nosniff"
  Report-To = '{"group":"default","max_age":31536000,"endpoints":[{"url":"https://ldesgoui.report-uri.com/a/d/g"}],"include_subdomains":true}'
  NEL = '{"report_to":"default","max_age":31536000,"include_subdomains":true}'
  Expect-CT = 'max-age=604800, report-uri="https://ldesgoui.report-uri.com/r/d/ct/enforce"'
